<template>
  <a-layout style="min-height: 100vh">
    <a-layout-header class="header">
      <a-flex class="header-bar" justify="space-between" align="center">
        <div class="logo" />
        <MyIcon type="icon-phone-signal-full" class="red" />
        <a-avatar style="background-color: #87d068">
          <template #icon>
            <UserOutlined />
          </template>
        </a-avatar>
      </a-flex>
    </a-layout-header>
    <a-layout>
      <a-layout-sider v-model:collapsed="collapsed" collapsible>
        <a-menu
          theme="dark"
          mode="inline"
          v-model:selectedKeys="permission.selectedKeys"
          :open-keys="permission.openKeys"
          :items="menuItems"
          @click="handleClick"
          @openChange="handleOpenChange"
        />
      </a-layout-sider>
      <a-layout class="main">
        <a-layout-content style="margin: 0 16px">
          <a-breadcrumb style="margin: 16px 0">
            <a-breadcrumb-item>User</a-breadcrumb-item>
            <a-breadcrumb-item>Bill</a-breadcrumb-item>
          </a-breadcrumb>
          <router-view />
        </a-layout-content>
        <a-layout-footer style="text-align: center">
          Design ©2018 Created by UED
        </a-layout-footer>
      </a-layout>
    </a-layout>
  </a-layout>
</template>

<script setup>
import { reactive, ref, h } from "vue";
import { useRouter } from "vue-router";
import { usePermissionStore } from "@/stores/permission";
import {
  UserOutlined,
  MailOutlined,
  DesktopOutlined,
} from "@ant-design/icons-vue";
import { createFromIconfontCN } from "@ant-design/icons-vue";
import menus from "@/router/modules/menus";

const MyIcon = createFromIconfontCN({
  scriptUrl: "//at.alicdn.com/t/font_2997331_lfbuvr1rp0s.js", // generated by iconfont.cn
});

const router = useRouter();
const permission = usePermissionStore();

const collapsed = ref(false);

const test = [];

const menuItems = ref([...permission.menus]);

const state = reactive({
  selectedKeys: [],
  openKeys: [],
});

function handleClick({ key, keyPath, item: { originItemValue } }) {
  const len = keyPath.length;
  if (len === 1) {
    permission.openKeys = [];
  } else {
    permission.openKeys = [...keyPath].slice(0, -1);
  }
  permission.selectedKeys = keyPath;

  router.push(keyPath.join("/"));
}

function handleOpenChange(openKeys) {
  // console.log(openKeys);
}
</script>

<style lang="scss" scoped>
.red {
  color: red;
}

.header-inner {
  height: 100%;
}
.logo {
  width: 160px;
  height: 64px;
  color: #fff;
  background: url(/logo.png) no-repeat 50%;
}
.main {
  height: calc(100vh - 64px);
  overflow: auto;
}
</style>
